activity_id: 8

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 7
    learning_rate: 0.33
    num_leaves: 84
    min_child_samples: 37
    lambda_l1: 46.63
    lambda_l2: 24.44
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 2.53
    max_depth: 8
    min_child_weights: 0
    subsample: 0.5
    gamma: 8.5
    lambda: 0.22
    alpha: 0.31
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 371
    max_depth: 5
    min_samples_split: 8
    max_features: 0.5
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1
    learning_rate_init: 0.001
    max_iter: 200
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha:  1.9
    learning_rate_init: 0.06326
    max_iter: 879
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.5
    learning_rate_init: 0.00537
    max_iter: 391
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 964
    C: 383.45
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 964
    C: 383.45
svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009