activity_id: 10

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 8
    learning_rate: 0.51
    num_leaves: 67
    min_child_samples: 43
    lambda_l1: 49.2
    lambda_l2: 75.28
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 2.03
    max_depth: 10
    min_child_weights: 9
    subsample: 0.9
    gamma: 5.2
    lambda: 0.94
    alpha: 0.61
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 108
    max_depth: 5
    min_samples_split: 4
    max_features: 0.61
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.3
    learning_rate_init: 0.09295
    max_iter: 448
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1
    learning_rate_init: 0.001
    max_iter: 200
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.1
    learning_rate_init: 0.01253
    max_iter: 402
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 30
    C: 832.62
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 30
    C: 832.62

svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009