activity_id: 9

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 7
    learning_rate: 0.93
    num_leaves: 37
    min_child_samples: 30
    lambda_l1: 51.37
    lambda_l2: 56.21
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 0.59
    max_depth: 4
    min_child_weights: 0
    subsample: 0.8
    gamma: 5.86
    lambda: 0.72
    alpha: 0.57
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 108
    max_depth: 10
    min_samples_split: 9
    max_features: 0.5
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1
    learning_rate_init: 0.001
    max_iter: 200
#    early_stopping: true
#    random_state: 0
#    verbose: 0
#    alpha: 0.2
#    learning_rate_init: 0.07485
#    max_iter: 784
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1
    learning_rate_init: 0.001
    max_iter: 200
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha:  1.5
    learning_rate_init: 0.04362
    max_iter: 696
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 13
    C: 426.54
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 13
    C: 426.54

svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009