activity_id: comb_4

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    seed: 0
    max_depth: 10
    learning_rate: 0.46
    num_leaves: 428
    min_child_samples: 40
    lambda_l1: 28.17
    lambda_l2: 98.19
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 2.01
    max_depth: 7
    min_child_weights: 1
    subsample: 0.8
    gamma: 1.13
    lambda: 0.35
    alpha: 0.25
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 194
    max_depth: 5
    min_samples_split: 8
    max_features: 0.501
mlp_2:  #  paper used
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.5
    learning_rate_init: 0.00242
    max_iter: 381
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.1
    learning_rate_init: 0.02399
    max_iter: 469
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.6
    learning_rate_init: 0.02878
    max_iter: 575
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 336
    C: 431.89
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 336
    C: 431.89
svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009