activity_id: 7

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 8
    learning_rate: 0.29
    num_leaves: 232
    min_child_samples: 56
    lambda_l1: 1.75
    lambda_l2: 77.17
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 1.62
    max_depth: 7
    min_child_weights: 4
    subsample: 0.7
    gamma: 0.8
    lambda: 0.06
    alpha: 0.26
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 199
    max_depth: 7
    min_samples_split: 8
    max_features: 0.51
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.3
    learning_rate_init: 0.06414
    max_iter: 768
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.7
    learning_rate_init: 0.03717
    max_iter: 603
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 2.0
    learning_rate_init: 0.03024
    max_iter: 593
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 42
    C: 262.55
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 42
    C: 262.55

svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009