activity_id: 1

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    seed: 0
    max_depth: 8
    learning_rate: 0.64
    num_leaves: 151
    min_child_samples:  37
    lambda_l1: 63.91
    lambda_l2: 39.91
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 2.02
    max_depth: 5
    min_child_weights: 8
    subsample: 0.7
    gamma: 9.52
    lambda: 0.09
    alpha: 0.75
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 385
    max_depth: 6
    min_samples_split: 6
    max_features: 0.5331589578098774
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.4
    learning_rate_init: 0.0367
    max_iter: 349
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.2
    learning_rate_init: 0.03133
    max_iter: 665
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.5
    learning_rate_init: 0.02079
    max_iter: 502
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 993
    C: 929.32
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 993
    C: 929.32
svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009