activity_id: 4

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 6
    learning_rate: 0.22
    num_leaves: 5
    min_child_samples: 49
    lambda_l1: 96.6
    lambda_l2: 80.38
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 1.37
    max_depth: 5
    min_child_weights: 0
    subsample: 0.8
    gamma: 1.6
    lambda: 0.24
    alpha: 0.63
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 138
    max_depth: 5
    min_samples_split: 5
    max_features: 0.826
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 2.0
    learning_rate_init: 0.03862
    max_iter: 771
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.3
    learning_rate_init: 0.01157
    max_iter: 568
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.7
    learning_rate_init: 0.03364
    max_iter: 847
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 18
    C: 567.810
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 18
    C: 567.810
svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009