activity_id: 11

lgbm:
  params:
    objective: "multiclass"
    num_class: 4
    metric: "multi_logloss"
    verbosity: -1
    boosting_type: "gbdt"
    num_threads: -1
    max_depth: 6
    learning_rate: 0.55
    num_leaves: 3
    min_child_samples: 58
    lambda_l1: 68.84
    lambda_l2: 33.3
xgb:
  params:
    objective: "multi:softprob"
    num_class: 4  # 这个值可以根据具体情况调整
    eval_metric: 'mlogloss'
    verbosity: 0
    seed: 0
    num_boost_round: 5000
    eta: 1.3
    max_depth: 5
    min_child_weights: 0
    subsample: 1.0
    gamma: 2.66
    lambda: 0.29
    alpha: 0.44
rf:
  params:
    bootstrap: True
    random_state: 0
    n_jobs: -1
    verbose: 0
    n_estimators: 499
    max_depth: 7
    min_samples_split: 4
    max_features: 0.52
mlp_2:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1.5
    learning_rate_init: 0.01542
    max_iter: 549
mlp_4:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 1
    learning_rate_init: 0.05681
    max_iter: 434
mlp_8:
  params:
    early_stopping: true
    random_state: 0
    verbose: 0
    alpha: 0.1
    learning_rate_init: 0.00234
    max_iter: 447
logistic_l1:
  params:
    penalty: l1
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 368
    C: 2.35
logistic_l2:
  params:
    penalty: l2
    solver: saga
    random_state: 0
    n_jobs: -1
    verbose: 0
    max_iter: 368
    C: 2.35

svm_l1:
  params:
    penalty: l1
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
svm_l2:
  params:
    penalty: l2
    loss: squared_hinge
    dual: false
    C: 0.01
    random_state: 0
    max_iter: 1000
    verbose: 0
knn:
  params:
    n_neighbors: 10
    weights: distance
    algorithm: auto
    n_jobs: -1
bayes:
  params:
    priors: null
    var_smoothing: 0.000000009